/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on Jul 17, 2011, 3:35:36 AM
 */

package ide;
import ide.*;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.Default;
import java.awt.event.*;
import java.lang.reflect.Method;
import java.net.*;
import javax.swing.JLabel;
import java.awt.*;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.tree.*;
/////
import java.lang.reflect.*;
import java.awt.*;
import java.awt.event.*;
import java.lang.reflect.Method;
import java.net.*;
import javax.swing.JLabel;
import java.awt.*;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.text.Document;
import javax.swing.tree.*;
import javax.swing.undo.*;
import javax.swing.undo.UndoManager;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.Document;
import javax.swing.text.JTextComponent;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import javax.tools.*;
import java.io.*;
import java.awt.TextComponent.*;
import java.util.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionEvent;
import javax.swing.text.BadLocationException;
import javax.swing.GroupLayout.*;
/**
////
/**
 *
 * @author GURJEET
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /** Creates new form NewJFrame1 */
    public NewJFrame1() {
        initComponents();
        //jToolBar1.setVisible(false);
//        jInternalFrame1.setVisible(false);
       // jTabbedPane2.setEnabled(false);
        //jTextField2.setText("C:\\IDE\\");
       // jTextField1.setText(getTitle());

        
        String st = new front().username;
         jLabel14.setText(new front().username);

          jLabel4.setEnabled(false);
        jPanel2.setVisible(true);
       jLabel9.setVisible(false);
      // jTextArea1.setEnabled(false);
/*
   jTextArea1.setText("class "+getTitle()+ "\n " );
   jTextArea1.append("   { \n");
    jTextArea1.append("      public static void main(String args[])\n");
    jTextArea1.append("        {\n");
    jTextArea1.append("  }\n");
    jTextArea1.append("        }\n");*/
   
 //  { public static void main(String args[]){     }  }");
   //jTextArea1.setEnabled(false);
  /* Container cp = getContentPane();
   DefaultMutableTreeNode top = new DefaultMutableTreeNode("options");
    DefaultMutableTreeNode a = new DefaultMutableTreeNode("A");
    top.add(a);
    JTree tree = new JTree(top);
    int v =100;
     int h =200;
    // jScrollPane jsp = new jScrollPane();
    
     jScrollPane3.setVisible(true);
     jScrollPane3.add(tree);
     
     cp.add(jScrollPane3);*/

//String cuttext="";
     //// undo redo of text //////
    final UndoManager undo = new UndoManager();
Document doc = jTextArea1.getDocument();

doc.addUndoableEditListener(new UndoableEditListener() {
    public void undoableEditHappened(UndoableEditEvent evt) {
        undo.addEdit(evt.getEdit());
    }
});

jTextArea1.getActionMap().put("Undo",
    new AbstractAction("Undo") {
        public void actionPerformed(ActionEvent evt) {
            try {
                if (undo.canUndo()) {
                    undo.undo();
                }
            } catch (CannotUndoException e) {
            }
        }
   });  

   jTextArea1.getInputMap().put(KeyStroke.getKeyStroke("control Z"), "Undo");

// Create a redo action and add it to the text component
jTextArea1.getActionMap().put("Redo",
    new AbstractAction("Redo") {
        public void actionPerformed(ActionEvent evt) {
            try {
                if (undo.canRedo()) {
                    undo.redo();
                }
            } catch (CannotRedoException e) {
            }
        }
    });

// Bind the redo action to ctl-Y
jTextArea1.getInputMap().put(KeyStroke.getKeyStroke("control Y"), "Redo"); 
     ///////////////////////////////
     




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu10.setText("File");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar3.add(jMenu11);

        jMenu12.setText("File");
        jMenuBar4.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar4.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar5.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar5.add(jMenu15);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setText("Recent Projects...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setMaximumRowCount(25);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<-----DEFAULT------->" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addComponent(jComboBox2, 0, 201, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane2.setForeground(new java.awt.Color(204, 51, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTextArea1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextArea1InputMethodTextChanged(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Code..", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Design", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\new project.jpg")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\openprojct.jpg")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\save.jpg")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\undo.jpg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\redo.jpg")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\run main projct.jpg")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        jTextField2.setText("Search your text here..");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setForeground(new java.awt.Color(51, 0, 204));
        jLabel8.setText("Directory....");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Project's Name");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\debugmain.jpg")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10.setText("Output :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setForeground(new java.awt.Color(204, 0, 102));
        jLabel11.setText("Classes to be used..");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setMaximumRowCount(29);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<-----DEFAULT------->" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 256, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );

        jLabel9.setText("jLabel9");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setForeground(new java.awt.Color(204, 51, 0));
        jLabel12.setText("No. of Errors :");

        jLabel14.setText("jLabel14");

        jLabel15.setText("User Name :-");

        jButton2.setText("Log Out..");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));

        jMenu1.setMnemonic('f');
        jMenu1.setText("FILEE");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu1KeyPressed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\new projecct.jpg")); // NOI18N
        jMenuItem1.setMnemonic('i');
        jMenuItem1.setText("NEW PROJECT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\openproject.jpg")); // NOI18N
        jMenuItem3.setText("OPEN PROJECT");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\bar2\\save.jpg")); // NOI18N
        jMenuItem4.setText("Save");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Print");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Exit");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem7MousePressed(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("FILE EDITING");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\undo.jpg")); // NOI18N
        jMenuItem9.setText("UNDO");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem9MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\redo.jpg")); // NOI18N
        jMenuItem10.setText("REDOOO");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\cut.jpg")); // NOI18N
        jMenuItem11.setText("Cut");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem11MousePressed(evt);
            }
        });
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\copy.jpg")); // NOI18N
        jMenuItem12.setText("Copy");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem12MousePressed1(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\pasete.jpg")); // NOI18N
        jMenuItem8.setText("Paste");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Window");

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem27.setText("Projectss");
        jMenuItem27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem27MousePressed(evt);
            }
        });
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem27);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Help");

        jMenuItem31.setText("Help Contents");
        jMenu9.add(jMenuItem31);

        jMenuItem33.setText("Keyboard Shortcuts");
        jMenuItem33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem33MousePressed(evt);
            }
        });
        jMenu9.add(jMenuItem33);

        jMenuItem17.setText("Report Issue");
        jMenuItem17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem17MousePressed(evt);
            }
        });
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem17);

        jMenuItem18.setText("About");
        jMenuItem18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem18MousePressed(evt);
            }
        });
        jMenu9.add(jMenuItem18);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("OPTIONS");

        jMenuItem2.setText("Transfer byte code");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem5.setText("CHECK RESPONSE");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("RUN FILE HERE");

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\runmainproject.jpg")); // NOI18N
        jMenuItem16.setText("Run File");
        jMenuItem16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem16MousePressed(evt);
            }
        });
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem19.setIcon(new javax.swing.ImageIcon("C:\\Users\\GURJEET\\Desktop\\New folder\\debugmain.jpg")); // NOI18N
        jMenuItem19.setText("Test Project");
        jMenuItem19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem19MousePressed1(evt);
            }
        });
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel10)
                                    .addGap(214, 214, 214)
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(455, 455, 455)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("agaga");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setText(null);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        new NewProject().setVisible(true);
        System.out.println("hhhhh");
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
///System.exit(0);
// System.out.println("hhhhh");
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void jMenuItem7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MousePressed
        // TODO add your handling code here:
        System.exit(0);
 System.out.println("hhhhh");
    }//GEN-LAST:event_jMenuItem7MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
Connection con = null;
Statement st;
ResultSet rs;

try
{
    Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");
    st = con.createStatement();
    rs = st.executeQuery("Select filename from newfile");

   while(rs.next())
   {
           jComboBox2.addItem(rs.getString("filename"));
       
       
   }
 //else
   //  jOptionPane1.showMessageDialog(this, "Wrong details entered.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
           rs.close();
           con.close();

}
catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
     ;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem3KeyPressed
        // TODO add your handling code here:
        //jTextField2.setText(null);
    }//GEN-LAST:event_jMenuItem3KeyPressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        // TODO add your handling code here:
       /* jTextArea1.setEnabled(true);
         FileDialog fd = new FileDialog(this,"OPEN",FileDialog.LOAD);
          fd.setVisible(true);
          String dir= fd.getDirectory();
          //
            d= fd.getDirectory();
          //

          String file= fd.getFile();
          //
            f= fd.getFile();
          //

          String s = dir+file;
          setTitle(file);
          jTextField2.setText(d);
          jTextField1.setText(f);
          try{
              FileInputStream fin = new FileInputStream(s);
         int ch;
         String s11="";
   
      FileInputStream fstream = new FileInputStream(s);
      while ((ch = fin.read()) != -1)
         s11=s11+(char)ch;
      fin.close();
     String j = s11;
     jTextArea1.setText(j);
// jTextField1.setText(j);
    
        }
          catch(Exception e)
          {
              System.out.println(e);
          }*/

             //FileInputStream f = new FileInputStream(fd);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1KeyPressed

    private void jMenuItem4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem4KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuItem4KeyPressed

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
        // TODO add your handling code here:
         /* String a = getTitle();
    
        
        String result="";
       
       // jTextField3.setText(a);
      /*   Connection con = null;
          Statement st;
          ResultSet rs;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");
               
               st=con.createStatement();
               rs=st.executeQuery("select * from newfile where filename=a");
               while(rs.next())
               {
                   String direc = rs.getString("dir");
                   result = direc+a;
               }
              con.close();
jTextField3.setText(result);
             
        }
        catch(Exception e)
        {

        }*/
   /////////////
      /*  try{
            String filname = d+f;
            FileWriter fr = new FileWriter(filname);
             BufferedWriter br = new BufferedWriter(fr);
             br.write(jTextArea1.getText());
             br.close();
        }
         catch(Exception e)
        {
             System.out.println(e);
         }*/
////////////////////

    }//GEN-LAST:event_jMenuItem4MousePressed

    private void jMenuItem18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem18MousePressed
        // TODO add your handling code here:
        new contacts().setVisible(true);
    }//GEN-LAST:event_jMenuItem18MousePressed

    private void jMenuItem11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MousePressed
        // TODO add your handling code here:

        cuttext=jTextArea1.getSelectedText();
			int cutindex=jTextArea1.getText().indexOf(cuttext);
			jTextArea1.replaceRange("",cutindex,cutindex+cuttext.length());


              //  originaltext = jTextArea1.getText();

            
    }//GEN-LAST:event_jMenuItem11MousePressed

    private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
        // TODO add your handling code here:
        getcaretpos=jTextArea1.getCaretPosition();

              jTextArea1.insert(cuttext, getcaretpos);
      // originaltext = jTextArea1.getText();
		//	jTextArea1.insertText(cuttext,getcaretpos);
    }//GEN-LAST:event_jMenuItem8MousePressed

    private void jMenuItem12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MousePressed
        // TODO add your handling code here:

          cuttext = jTextArea1.getSelectedText();
 //originaltext = jTextArea1.getText();
       
    }//GEN-LAST:event_jMenuItem12MousePressed

    private void jMenuItem9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MousePressed
        // TODO add your handling code here:
     /*   if(!originaltext.equals(jTextArea1.getText()))
        {
            jTextArea1.setText(originaltext);
        }*/
    }//GEN-LAST:event_jMenuItem9MousePressed

    private void jMenuItem16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem16MousePressed
/*        // TODO add your handling code here:
       //String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath","C:\\","Array2"};
      jTextArea2.setText("");
        {
          String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
            }



String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath",d,classname[1]};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
while(sc.hasNextLine())
{
    jLabel9.setText(sc.nextLine());
  //  jTextArea1.setText(sc.nextLine());
 //System.out.println(sc.nextLine());
 flag=false;

}
if(flag)
 {
    //jTextArea1.setText("done!!!!");
  System.out.println("Done !!");
 }
/////
     InputStream stderr = ps.getInputStream();
            InputStreamReader isr = new InputStreamReader(stderr);
            BufferedReader br = new BufferedReader(isr);
            String line = null;


    while ( (line = br.readLine()) != null)
         {       
                  jTextArea2.append(line+"\n");
        System.out.println(line);
            //System.out.println("");
    }

sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
        }
  //  jTextArea1.setText("you have not compiled or error in compilation");*/

    }//GEN-LAST:event_jMenuItem16MousePressed

    private void jMenuItem19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem19MousePressed
        // TODO add your handling code here:
          //String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\","C:\\IDE\\hello.java"};
            jTextArea2.setText("");

        jTextField1.setText(d);
         jTextField1.setText(f);


            String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
        }
                 classname[1]= classname[1]+".java";

       // String f = getTitle()+".java";

       //    String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\","C:\\IDE\\"+classname[1]};
                   String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\",d+f};
             //      String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath",d,f};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
//String s="";

while(sc.hasNextLine())
{
 //   s=sc.nextLine();
    jTextArea2.append(sc.nextLine());
/*    jLabel9.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());
      jTextArea2.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());*/

 //System.out.println(sc.nextLine());


            flag=false;



}
if(flag)
 {  jLabel9.setVisible(true);
    jLabel9.setText("0");
    jTextArea2.setText("compiled");
  System.out.println("compiled");
 }
sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
    }//GEN-LAST:event_jMenuItem19MousePressed

    private void jMenuItem16MousePressed1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem16MousePressed1
        // TODO add your handling code here:
        {
          String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
            }



String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath",d,classname[1]};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
while(sc.hasNextLine())
{
    jLabel9.setText(sc.nextLine());
  //  jTextArea1.setText(sc.nextLine());
 //System.out.println(sc.nextLine());
 flag=false;

}
if(flag)
 {
    //jTextArea1.setText("done!!!!");
  System.out.println("Done !!");
 }
/////
     InputStream stderr = ps.getInputStream();
            InputStreamReader isr = new InputStreamReader(stderr);
            BufferedReader br = new BufferedReader(isr);
            String line = null;


    while ( (line = br.readLine()) != null)
         {
                  jTextArea2.append(line);
               }

sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
        }
    }//GEN-LAST:event_jMenuItem16MousePressed1

    private void jMenuItem33KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem33KeyPressed
        // TODO add your handling code here:
       // jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem33KeyPressed

    private void jMenuItem33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem33MousePressed
        // TODO add your handling code here:
        // jInternalFrame1.setVisible(true);
        new scuts().setVisible(true);
    }//GEN-LAST:event_jMenuItem33MousePressed

    private void jMenuItem17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem17MousePressed
        // TODO add your handling code here:
        new ReportIssue().setVisible(true);
     //   setVisible(false);
    }//GEN-LAST:event_jMenuItem17MousePressed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        //save ko enable kia hai
        jLabel4.setEnabled(true);
        //  originaltext = jTextArea1.getText();
        try {
           // System.out.println("display = "+ new JFrame().getClass().getSuperclass());
            //BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
            //test();
            Class C = Class.forName("java.lang.System");
            Method M[] = C.getDeclaredMethods();
            //Method M[] = C.getDeclaredMethods();
            for(int i=0;i<M.length;i++) {
                // System.out.println(M[i].toString());
                jComboBox1.addItem(M[i].toString());
                System.out.println(M[i].toString());
                //jTextArea3.append(M[i].toString()+"\n ");

            }
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_jTextArea1KeyTyped
    private void jTextArea1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextArea1InputMethodTextChanged
        // TODO add your handling code here:
        //  originaltext = jTextArea1.getText();
    }//GEN-LAST:event_jTextArea1InputMethodTextChanged

    private void jTextArea1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextArea1CaretPositionChanged
        // TODO add your handling code here:
        //  originaltext = jTextArea1.getText();
        //
}//GEN-LAST:event_jTextArea1CaretPositionChanged

    private void jMenuItem27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem27MousePressed
        // TODO add your handling code here:
      /*  Connection con = null;
Statement st;
ResultSet rs;

try
{
    Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");
    st = con.createStatement();
    rs = st.executeQuery("Select filename from newfile");

   while(rs.next())
   {
           jComboBox2.addItem(rs.getString("filename"));


   }
 //else
   //  jOptionPane1.showMessageDialog(this, "Wrong details entered.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
           rs.close();
           con.close();

}
catch(Exception e)
        {
            System.out.println(e.getMessage());
        }*/
       
    }//GEN-LAST:event_jMenuItem27MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
         jTextArea1.setEnabled(true);
          new NewProject().setVisible(true);
           jTabbedPane2.setEnabled(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
            jTextArea1.setEnabled(true);
         FileDialog fd = new FileDialog(this,"OPEN",FileDialog.LOAD);
          fd.setVisible(true);
          String dir= fd.getDirectory();
          //
            d= fd.getDirectory();
          //

          String file= fd.getFile();
          //
            f= fd.getFile();
          //

          String s = dir+file;
          setTitle(file);
          jTextField2.setText(d);
          jTextField1.setText(f);
          try{
              FileInputStream fin = new FileInputStream(s);
         int ch;
         String s11="";

      FileInputStream fstream = new FileInputStream(s);
      while ((ch = fin.read()) != -1)
         s11=s11+(char)ch;
      fin.close();
     String j = s11;
     jTextArea1.setText(j);
// jTextField1.setText(j);

        }
          catch(Exception e)
          {
              System.out.println(e);
          }

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
         String a = getTitle();


        String result="";

       // jTextField3.setText(a);
      /*   Connection con = null;
          Statement st;
          ResultSet rs;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");

               st=con.createStatement();
               rs=st.executeQuery("select * from newfile where filename=a");
               while(rs.next())
               {
                   String direc = rs.getString("dir");
                   result = direc+a;
               }
              con.close();
jTextField3.setText(result);

        }
        catch(Exception e)
        {

        }*/
   /////////////
        try{
            String filname = d+f;
            FileWriter fr = new FileWriter(filname);
             BufferedWriter br = new BufferedWriter(fr);
             br.write(jTextArea1.getText());
             br.close();
        }
         catch(Exception e)
        {
             System.out.println(e);
         }
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
         // TODO add your handling code here:
          //String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\","C:\\IDE\\hello.java"};

        jTextField1.setText(d);
         jTextField1.setText(f);


            String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
        }
                 classname[1]= classname[1]+".java";

       // String f = getTitle()+".java";

       //    String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\","C:\\IDE\\"+classname[1]};
                   String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\",d+f};
             //      String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath",d,f};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
//String s="";

while(sc.hasNextLine())
{
 //   s=sc.nextLine();
    jTextArea2.setText(sc.nextLine());
    jLabel9.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());
      jTextArea2.setText(sc.nextLine());
    jTextArea2.setText(sc.nextLine());

 //System.out.println(sc.nextLine());


            flag=false;



}
if(flag)
 {  jLabel9.setVisible(true);
    jLabel9.setText("0");
    jTextArea2.setText("compiled");
  System.out.println("compiled");
 }
sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
         // TODO add your handling code here:
       //String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath","C:\\","Array2"};
 jTextArea2.setText("");
        {
          String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
            }



String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath",d,classname[1]};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
while(sc.hasNextLine())
{
    jLabel9.setText(sc.nextLine());
  //  jTextArea1.setText(sc.nextLine());
 //System.out.println(sc.nextLine());
 flag=false;

}
if(flag)
 {
    //jTextArea1.setText("done!!!!");
  System.out.println("Done !!");
 }
/////
     InputStream stderr = ps.getInputStream();
            InputStreamReader isr = new InputStreamReader(stderr);
            BufferedReader br = new BufferedReader(isr);
            String line = null;


    while ( (line = br.readLine()) != null)
         {
                  jTextArea2.append(line+"\n");
        System.out.println(line);
        jLabel9.setText((""));
            //System.out.println("");
    }

sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
        }
  //  jTextArea1.setText("you have not compiled or error in compilation");
    }//GEN-LAST:event_jLabel7MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    jTextArea1.setEnabled(true);
         FileDialog fd = new FileDialog(this,"OPEN",FileDialog.LOAD);
          fd.setVisible(true);
          String dir= fd.getDirectory();
          //
            d= fd.getDirectory();
          //

          String file= fd.getFile();
          //
            f= fd.getFile();
          //

          String s = dir+file;
          setTitle(file);
          jTextField2.setText(d);
          jTextField1.setText(f);
          try{
              FileInputStream fin = new FileInputStream(s);
         int ch;
         String s11="";

      FileInputStream fstream = new FileInputStream(s);
      while ((ch = fin.read()) != -1)
         s11=s11+(char)ch;
      fin.close();
     String j = s11;
     jTextArea1.setText(j);
// jTextField1.setText(j);

        }
          catch(Exception e)
          {
              System.out.println(e);
          }     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
          jTextArea1.setEnabled(true);
          new NewProject().setVisible(true);
           jTabbedPane2.setEnabled(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          jTextArea1.setEnabled(true);
          new NewProject().setVisible(true);
           jTabbedPane2.setEnabled(true);
           newfrmetonewproforusername = jLabel14.getText();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         String a = getTitle();


        String result="";

       // jTextField3.setText(a);
      /*   Connection con = null;
          Statement st;
          ResultSet rs;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");

               st=con.createStatement();
               rs=st.executeQuery("select * from newfile where filename=a");
               while(rs.next())
               {
                   String direc = rs.getString("dir");
                   result = direc+a;
               }
              con.close();
jTextField3.setText(result);

        }
        catch(Exception e)
        {

        }*/
   /////////////
        try{
            String filname = d+f;
            FileWriter fr = new FileWriter(filname);
             BufferedWriter br = new BufferedWriter(fr);
             br.write(jTextArea1.getText());
             br.close();
        }
         catch(Exception e)
        {
             System.out.println(e);
         }
////////////////////
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        /*   cuttext=jTextArea1.getSelectedText();
			int cutindex=jTextArea1.getText().indexOf(cuttext);
			jTextArea1.replaceRange("",cutindex,cutindex+cuttext.length());*/
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
       /*   getcaretpos=jTextArea1.getCaretPosition();
              jTextArea1.insert(cuttext, getcaretpos);*/
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:C:\\IDE\\
      
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        String s = (String)evt.getItem();
         try{
              FileInputStream fin = new FileInputStream("C://IDE//"+s);
         int ch;
         String s11="";

    
      while ((ch = fin.read()) != -1)
      {
          s11 = s11 + (char) ch;}
      fin.close();
     String j = s11;
     jTextArea1.setText(j);
// jTextField1.setText(j);

        }
          catch(Exception e)
          {
              System.out.println(e);
          }
        d = "C://IDE//";
        f = s;
        setTitle(s);
        jTextField1.setText(s);
      //  avail = new NewJFrame1().f.substring(1,f.length()-5);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jMenuItem12MousePressed1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MousePressed1
        // TODO add your handling code here:
        cuttext = jTextArea1.getSelectedText();
    }//GEN-LAST:event_jMenuItem12MousePressed1

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
         //String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath","C:\\","Array2"};
      jTextArea2.setText("");
        {
          String s=jTextArea1.getText();
            String classname[] = new String[1000];
        StringTokenizer st = new StringTokenizer(s);

            for (int i = 0; st.hasMoreTokens(); i++)
            {
                classname[i] = st.nextToken();
            }



String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\java","-classpath",d,classname[1]};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
while(sc.hasNextLine())
{
    jLabel9.setVisible(true);
    jLabel9.setText(sc.nextLine());
  //  jTextArea1.setText(sc.nextLine());
 //System.out.println(sc.nextLine());
 flag=false;

}
if(flag)
 {
    jLabel1.setText("done!!!!");
  System.out.println("Done !!");
 }
/////
     InputStream stderr = ps.getInputStream();
            InputStreamReader isr = new InputStreamReader(stderr);
            BufferedReader br = new BufferedReader(isr);
            String line = null;


    while ( (line = br.readLine()) != null)
         {
                  jTextArea2.append(line+"\n");
        System.out.println(line);
        jLabel9.setText((""));
            //System.out.println("");
    }

sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
        }
  //  jTextArea1.setText("you have not compiled or error in compilation");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19MousePressed1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem19MousePressed1
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem19MousePressed1

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
Statement st;
ResultSet rs;

try
{
    Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IDE","root","123456");
    st = con.createStatement();
    rs = st.executeQuery("Select filename from newfile");

   while(rs.next())
   {
           jComboBox2.addItem(rs.getString("filename"));


   }
 //else
   //  jOptionPane1.showMessageDialog(this, "Wrong details entered.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
           rs.close();
           con.close();

}
catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\",d+f};
//String commands[]= {"C:\\Program Files\\Java\\jdk1.6.0_15\\bin\\javac","-classpath","C:\\","C:\\IDE\\hello.java"};
try
{
 Process ps=Runtime.getRuntime().exec(commands);
 Scanner sc=new Scanner(ps.getErrorStream());
boolean flag=true;
long count=0;
while(sc.hasNextLine())
{

 jTextArea2.append(sc.nextLine()+"\n");
 count = count+1;
 //value = value + sc.nextLine();
 flag=false;

}
//jLabel9.setText(value);
if(flag)
 {
    jTextArea2.setText("");
   jTextArea2.append("compiled");
   jLabel9.setText("");
 }
String err ="";
if(jTextArea2.getText()!="compiled")
{
    String var = jTextArea2.getText();
     err = var.substring(var.length()-9,var.length());
}
jLabel9.setVisible(true);
jLabel9.setText(err);

/*String co = String.valueOf(count);
jLabel9.setVisible(true);
jLabel9.setText(co);*/

sc.close();

}
catch(Exception e)
{
System.out.println(e.getMessage());
}
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
      int k=evt.getKeyCode();
      switch(k)
      {
          case KeyEvent.VK_SPACE:
              

      }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new tranfer().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Responses().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new front().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
     public String cuttext="";
     int getcaretpos=0,setcaretpos=0;
     public String originaltext="class { public static void main(String args[]){     }  }";
     public String d="";
      public String f="";
      public  static  String avail ="";
      public static String newfrmetonewproforusername ="";
}
